# Inserts a blank line between shell prompts
add_newline = true

format = '''[‚ï≠‚îÄ‚îÄ $os \([$username@$hostname](bold blue)\)-\[$directory\]-($kubernetes)(-$git_branch$git_metrics$git_status)(-$nix_shell)](blue) $cmd_duration
[‚ï∞‚îÄ](blue)[$shell](bold blue) '''

# A minimal left prompt
# format = """$directory$character"""
# format = """$os$username@$hostname $kubernetes $directory $git_branch $git_status """
palette = "catppuccin_mocha"
# move the rest of the prompt to the right
right_format = '$status'
command_timeout = 1000

# [directory]
# truncation_length = 3
# truncation_symbol = '‚Ä¶/'
# truncate_to_repo = true
# style = 'bold white'
# format = '[$path]($style)[$read_only]($read_only_style)'

# Shows current directory
[directory]
truncation_length = 3
truncation_symbol = '‚Ä¶/'
home_symbol = 'Û∞ãú ~'
read_only_style = '197'
read_only = ' ÔÄ£ '
format = '[$path]($style)[$read_only]($read_only_style)'

[character]
success_symbol = '[Œª](bold blue)'
error_symbol = '[Œª](bold red)'
# success_symbol = '[‚ùØ](bold blue)'
# error_symbol = '[‚ùØ](bold red)'
# Drop ugly default prompt characters
# [character]
# success_symbol = ''
# error_symbol = ''

[os]
# format = '[$symbol](bold white) '   
# format = '\[[$symbol]($style)\]'
format = '[$symbol]($style)'
disabled = false

[os.symbols]
Windows = 'Óò™ '
Arch = 'Û∞£á'
Ubuntu = 'Ôåõ'
Macos = 'Û∞Äµ'

# Shows the username
[username]
style_user = 'white bold'
style_root = 'red bold'
# format = '[$user]($style) '
# format = '\[[$user]($style)\]'
format = '$user($style)'
disabled = false
show_always = true

# Shows the hostname
[hostname]
ssh_only = false
# format = 'on [$hostname](bold yellow) '
format = '[$ssh_symbol](bold blue)$hostname'
disabled = false

# Shows current git branch
[git_branch]
style = 'bold green'
symbol = 'ÓÇ†'
# format = '[$symbol$branch(hello$banch)](bold green)'
format = '\[[$symbol$branch]($style)\]'
# symbol = 'Ôáí '
# format = 'via [$symbol$branch]($style)'
# truncation_length = 4
# truncation_symbol = '‚Ä¶/'
# style = 'bold green'

# Shows current git status
# [git_status]
# modified = '[‚úò](bold red)'
# up_to_date = 'up'
# format = '$up_to_date$modified$up_to_date'
[git_status]
# format = '([ \( $all_status$ahead_behind\)]($style) )'
format = '([\[$all_status$ahead_behind\]]($style))'
style = 'bold green'
conflicted = '[ÔÅ™ confliced=${count}](red)'
up_to_date = '[Û∞òΩ up-to-date](green)'
untracked = '[Û∞ãó untracked=${count}](red)'
ahead = 'ÔÇ™ ahead=${count}'
diverged = 'ÔÇ™ ahead=${ahead_count} ÔÇ´ behind=${behind_count}'
behind = 'ÔÇ´ behind=${count}'
stashed = '[Ôäã stashed=${count}](green)'
modified = '[Û∞õø modified=${count}](yellow)'
staged = '[Û∞êó staged=${count}](green)'
renamed = '[Û±ç∏ renamed=${count}](yellow)'
deleted = '[Û∞ç∂ deleted=${count}](red)'

# [aws]
# format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
# disabled = false
# style = 'bold blue'
# symbol = "ÓåΩ  "
#
# [golang]
# format = '[Óòß ](bold cyan)'

[kubernetes]
symbol = '‚ò∏ '
disabled = false
detect_files = ['Dockerfile']
# format = '[$context(\[$namespace\])]($style) '
format = '\[[$symbol$context( \($namespace\))]($style)\]'

# [docker_context]
# disabled = true
#
# [helm]
# disabled = true
#
# [python]
# disabled = true
#
# [nodejs]
# disabled = true
#
# [ruby]
# disabled = true
#
# [terraform]
# disabled = true

[cmd_duration]
min_time = 1_000
style = "bold dimmed yellow"
# format = '‚ó∑[$duration]($style) '
format = '\[[‚è± $duration]($style)\]'

[shell]
fish_indicator = 'Û∞à∫'
powershell_indicator = 'Ôë†_'
bash_indicator = '\$'
zsh_indicator = 'Œª'
unknown_indicator = '?'
disabled = false
format = '$indicator'

[status]
disabled = false

[aws]
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[bun]
format = '\[[$symbol]($style)\]'

[c]
format = '\[[$symbol($version(-$name))]($style)\]'

[cmake]
format = '\[[$symbol]($style)\]'

[cobol]
format = '\[[$symbol]($style)\]'

[conda]
format = '\[[$symbol$environment]($style)\]'

[crystal]
format = '\[[$symbol]($style)\]'

[daml]
format = '\[[$symbol]($style)\]'

[dart]
format = '\[[$symbol]($style)\]'

[deno]
format = '\[[$symbol]($style)\]'

[docker_context]
format = '\[[$symbol$context]($style)\]'

[dotnet]
format = '\[[$symbol(üéØ $tfm)]($style)\]'

[elixir]
format = '\[[$symbol($version \(OTP $otp_version\))]($style)\]'

[elm]
format = '\[[$symbol]($style)\]'

[erlang]
format = '\[[$symbol]($style)\]'

[fennel]
format = '\[[$symbol]($style)\]'

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

# [git_branch]
# format = '\[[$symbol$branch]($style)\]'

# [git_status]
# format = '([\[$all_status$ahead_behind\]]($style))'

[golang]
format = '\[[$symbol]($style)\]'

[gradle]
format = '\[[$symbol]($style)\]'

[guix_shell]
format = '\[[$symbol]($style)\]'

[haskell]
format = '\[[$symbol]($style)\]'

[haxe]
format = '\[[$symbol]($style)\]'

[helm]
format = '\[[$symbol]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[java]
format = '\[[$symbol]($style)\]'

[julia]
format = '\[[$symbol]($style)\]'

[kotlin]
format = '\[[$symbol]($style)\]'

# [kubernetes]
# format = '\[[$symbol$context( \($namespace\))]($style)\]'

[lua]
format = '\[[$symbol]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
format = '\[[$symbol$project]($style)\]'

[nim]
format = '\[[$symbol]($style)\]'

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
format = '\[[$symbol]($style)\]'

[ocaml]
format = '\[[$symbol(\($switch_indicator$switch_name\))]($style)\]'

[opa]
format = '\[[$symbol]($style)\]'

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

# [os]
# format = '\[[$symbol]($style)\]'

[package]
format = '\[[$symbol$version]($style)\]'

[perl]
format = '\[[$symbol]($style)\]'

[php]
format = '\[[$symbol]($style)\]'

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
format = '\[[$symbol]($style)\]'

[python]
format = '\[[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)\]'

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
format = '\[[$symbol]($style)\]'

[ruby]
format = '\[[$symbol]($style)\]'

[rust]
format = '\[[$symbol]($style)\]'

[scala]
format = '\[[$symbol]($style)\]'

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[swift]
format = '\[[$symbol]($style)\]'

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

# [username]
# format = '\[[$user]($style)\]'

[vagrant]
format = '\[[$symbol]($style)\]'

[vlang]
format = '\[[$symbol]($style)\]'

[zig]
format = '\[[$symbol]($style)\]'

[solidity]
format = '\[[$symbol]($style)\]'

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
